/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_viperpit_core_data_FlightData */

#ifndef _Included_de_viperpit_core_data_FlightData
#define _Included_de_viperpit_core_data_FlightData
#ifdef __cplusplus
extern "C" {
#endif
#undef de_viperpit_core_data_FlightData_FLIGHTDATA_VERSION
#define de_viperpit_core_data_FlightData_FLIGHTDATA_VERSION 117L
#undef de_viperpit_core_data_FlightData_RWRINFO_SIZE
#define de_viperpit_core_data_FlightData_RWRINFO_SIZE 512L
#undef de_viperpit_core_data_FlightData_CALLSIGN_LEN
#define de_viperpit_core_data_FlightData_CALLSIGN_LEN 12L
#undef de_viperpit_core_data_FlightData_MAX_CALLSIGNS
#define de_viperpit_core_data_FlightData_MAX_CALLSIGNS 32L
/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_viperpit_core_data_FlightData_init
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    isSet1
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_viperpit_core_data_FlightData_isSet1
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    isSet2
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_viperpit_core_data_FlightData_isSet2
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    isSet3
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_viperpit_core_data_FlightData_isSet3
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    isSetHSI
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_viperpit_core_data_FlightData_isSetHSI
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getx
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getx
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    gety
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_gety
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getz
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getz
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getxDot
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getxDot
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getyDot
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getyDot
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getzDot
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getzDot
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getalpha
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getalpha
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getbeta
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getbeta
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getgamma
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getgamma
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getpitch
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getpitch
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getroll
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getroll
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getyaw
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getyaw
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getmach
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getmach
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getkias
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getkias
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getvt
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getvt
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getgs
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getgs
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getwindOffset
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getwindOffset
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getnozzlePos
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getnozzlePos
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getinternalFuel
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getinternalFuel
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getexternalFuel
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getexternalFuel
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getfuelFlow
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getfuelFlow
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getrpm
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getrpm
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getftit
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getftit
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getgearPos
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getgearPos
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getspeedBrake
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getspeedBrake
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getepuFuel
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getepuFuel
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getoilPressure
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getoilPressure
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getlightBits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getlightBits
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    setheadPitch
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_setheadPitch
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    setheadRoll
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_setheadRoll
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    setheadYaw
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_setheadYaw
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getlightBits2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getlightBits2
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getlightBits3
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getlightBits3
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getChaffCount
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getChaffCount
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getFlareCount
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getFlareCount
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getNoseGearPos
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getNoseGearPos
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getLeftGearPos
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getLeftGearPos
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getRightGearPos
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getRightGearPos
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getAdiIlsHorPos
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getAdiIlsHorPos
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getAdiIlsVerPos
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getAdiIlsVerPos
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getcourseState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getcourseState
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getheadingState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getheadingState
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    gettotalStates
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_gettotalStates
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getcourseDeviation
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getcourseDeviation
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getdesiredCourse
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getdesiredCourse
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getdistanceToBeacon
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getdistanceToBeacon
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getbearingToBeacon
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getbearingToBeacon
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getcurrentHeading
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getcurrentHeading
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getdesiredHeading
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getdesiredHeading
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getdeviationLimit
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getdeviationLimit
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    gethalfDeviationLimit
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_gethalfDeviationLimit
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getlocalizerCourse
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getlocalizerCourse
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getairbaseX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getairbaseX
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getairbaseY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getairbaseY
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    gettotalValues
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_gettotalValues
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getTrimPitch
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getTrimPitch
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getTrimRoll
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getTrimRoll
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getTrimYaw
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getTrimYaw
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    gethsiBits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_gethsiBits
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getDEDLines
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_de_viperpit_core_data_FlightData_getDEDLines
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getInvert
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_de_viperpit_core_data_FlightData_getInvert
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getPFLLines
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_de_viperpit_core_data_FlightData_getPFLLines
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getPFLInvert
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_de_viperpit_core_data_FlightData_getPFLInvert
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getUFCTChan
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getUFCTChan
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getAUXTChan
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getAUXTChan
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getRwrObjectCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getRwrObjectCount
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getRWRsymbol
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_de_viperpit_core_data_FlightData_getRWRsymbol
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getbearing
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_de_viperpit_core_data_FlightData_getbearing
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getmissileActivity
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_de_viperpit_core_data_FlightData_getmissileActivity
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getmissileLaunch
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_de_viperpit_core_data_FlightData_getmissileLaunch
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getselected
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_de_viperpit_core_data_FlightData_getselected
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getlethality
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_de_viperpit_core_data_FlightData_getlethality
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getnewDetection
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_de_viperpit_core_data_FlightData_getnewDetection
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getfwd
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getfwd
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getaft
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getaft
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    gettotal
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_gettotal
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getVersionNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getVersionNum
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    setheadX
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_setheadX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    setheadY
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_setheadY
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    setheadZ
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_setheadZ
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    MainPower
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_MainPower
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    ufcTacanIsAA
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_viperpit_core_data_FlightData_ufcTacanIsAA
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    auxTacanIsAA
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_viperpit_core_data_FlightData_auxTacanIsAA
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    ufcTacanIsX
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_viperpit_core_data_FlightData_ufcTacanIsX
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    auxTacanIsX
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_viperpit_core_data_FlightData_auxTacanIsX
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    isSetAlt
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_viperpit_core_data_FlightData_isSetAlt
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    isSetPower
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_viperpit_core_data_FlightData_isSetPower
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    isSetBlink
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_viperpit_core_data_FlightData_isSetBlink
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getnozzlePos2
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getnozzlePos2
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getrpm2
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getrpm2
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getftit2
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getftit2
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getoilPressure2
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getoilPressure2
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getnavMode
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_de_viperpit_core_data_FlightData_getnavMode
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getAAUZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getAAUZ
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    gettacanInfo
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_viperpit_core_data_FlightData_gettacanInfo
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getAltCalReading
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getAltCalReading
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getaltBits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getaltBits
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getpowerBits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getpowerBits
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getblinkBits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getblinkBits
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getcmdsMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getcmdsMode
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getBupUhfPreset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getBupUhfPreset
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getBupUhfFreq
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getBupUhfFreq
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getcabinAlt
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getcabinAlt
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    gethydPressureA
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_gethydPressureA
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    gethydPressureB
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_gethydPressureB
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getcurrentTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getcurrentTime
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getvehicleACD
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_viperpit_core_data_FlightData_getvehicleACD
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getVersionNum2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_viperpit_core_data_FlightData_getVersionNum2
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getfuelFlow2
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getfuelFlow2
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getRwrInfo
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_viperpit_core_data_FlightData_getRwrInfo
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getlefPos
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getlefPos
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    gettefPos
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_gettefPos
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getvtolPos
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_viperpit_core_data_FlightData_getvtolPos
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getpilotsOnline
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_de_viperpit_core_data_FlightData_getpilotsOnline
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getpilotsCallsign
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_de_viperpit_core_data_FlightData_getpilotsCallsign
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getpilotsStatus
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_viperpit_core_data_FlightData_getpilotsStatus
  (JNIEnv *, jobject);

/*
 * Class:     de_viperpit_core_data_FlightData
 * Method:    getTextureData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_de_viperpit_core_data_FlightData_getTextureData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_viperpit_core_data_FlightData_LightBits */

#ifndef _Included_de_viperpit_core_data_FlightData_LightBits
#define _Included_de_viperpit_core_data_FlightData_LightBits
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_viperpit_core_data_FlightData_LightBits2 */

#ifndef _Included_de_viperpit_core_data_FlightData_LightBits2
#define _Included_de_viperpit_core_data_FlightData_LightBits2
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_viperpit_core_data_FlightData_LightBits3 */

#ifndef _Included_de_viperpit_core_data_FlightData_LightBits3
#define _Included_de_viperpit_core_data_FlightData_LightBits3
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_viperpit_core_data_FlightData_HsiBits */

#ifndef _Included_de_viperpit_core_data_FlightData_HsiBits
#define _Included_de_viperpit_core_data_FlightData_HsiBits
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_viperpit_core_data_FlightData_TacanSources */

#ifndef _Included_de_viperpit_core_data_FlightData_TacanSources
#define _Included_de_viperpit_core_data_FlightData_TacanSources
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_viperpit_core_data_FlightData_TacanBits */

#ifndef _Included_de_viperpit_core_data_FlightData_TacanBits
#define _Included_de_viperpit_core_data_FlightData_TacanBits
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_viperpit_core_data_FlightData_AltBits */

#ifndef _Included_de_viperpit_core_data_FlightData_AltBits
#define _Included_de_viperpit_core_data_FlightData_AltBits
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_viperpit_core_data_FlightData_PowerBits */

#ifndef _Included_de_viperpit_core_data_FlightData_PowerBits
#define _Included_de_viperpit_core_data_FlightData_PowerBits
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_viperpit_core_data_FlightData_BlinkBits */

#ifndef _Included_de_viperpit_core_data_FlightData_BlinkBits
#define _Included_de_viperpit_core_data_FlightData_BlinkBits
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_viperpit_core_data_FlightData_CmdsModes */

#ifndef _Included_de_viperpit_core_data_FlightData_CmdsModes
#define _Included_de_viperpit_core_data_FlightData_CmdsModes
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_viperpit_core_data_FlightData_NavModes */

#ifndef _Included_de_viperpit_core_data_FlightData_NavModes
#define _Included_de_viperpit_core_data_FlightData_NavModes
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_viperpit_core_data_FlightData_FlyStates */

#ifndef _Included_de_viperpit_core_data_FlightData_FlyStates
#define _Included_de_viperpit_core_data_FlightData_FlyStates
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
