export const AGENTS_CONNECT = "AGENTS_CONNECT";
export const AGENTS_DISCONNECT = "AGENTS_DISCONNECT";
export const CONFIGURATION_UPDATE = "CONFIGURATION_UPDATE";
export const STATES_INIT = "STATES_INIT";
export const STATES_UPDATE = "STATES_UPDATE";
